### ISSUE TITLE
Crashing when tryiing to copy a message

### ISSUE THREAD

**Issue by Lucasnakajima** [tierrif/chat-utils#43] opened 2023-12-11 20:40 UTC
whenever I press ctrl and  click to copy a message my game crashes here it is my crash report:

[crash-2023-12-11_20.37.27-client.txt](https://github.com/tierrif/chat-utils/files/13640751/crash-2023-12-11_20.37.27-client.txt)

**Comment by tierrif** [comment] 2023-12-11 20:53
Duplicate of #40

**Closed by tierrif** 2023-12-11 20:53 UTC
