### ISSUE TITLE
Attempting to copy chat freezes client

### ISSUE THREAD

**Issue by soultwistrune** [tierrif/chat-utils#22] opened 2023-05-07 20:32 UTC
When trying to right-click on a chat message, the game will freeze.

**Comment by tierrif** [comment] 2023-05-07 20:35
Please give us more details as this cannot be reproduced under my circumstances. The following information will be useful:
- Content of the right clicked message
- Other mods you're using in your client (especially this)
- Client version

Thanks.

**Comment by QarthO** [comment] 2023-07-11 16:38
I'm having the same issue. After clicking on a chat message, the client freezes and it requires me to restart the game completely.

This is the error in the console: [Render thread/ERROR]: Not allowed to run command with signed argument from click event: '/chatmacros <QarthO> hi'

I tried creating an empty instance with just the base mods and nothing else and it still crashes.

Using MultiMC:
- Minecraft Version 1.20.1
- Fabric Loader: 0.14.21

Mods:
- Chat Utils Mod: 1.9.1+1.20.1
- Cloth Config v11: 11.1.106
- Fabric API: 0.85.0+1.20.1
- Mod Menu: 7.1.0

Running on MacOS Ventura 13.4.1

Things to note, the text does actually copy to my clipboard. But the game crashes 😔

**Comment by QarthO** [comment] 2023-07-11 16:46
Hi! I’m having this issue in both multiplayer and in single player. The error is the same.

The message I sent was just “hi”

No special format or anything

**Comment by tierrif** [comment] 2023-07-11 18:21
I looked at logs, and the log you mentioned does show up, but it doesn't crash due to it. So this is definitely not the reason why the client is crashing:
`[19:19:50] [Render thread/ERROR] (Minecraft) Not allowed to run command with signed argument from click event:`

**Comment by tierrif** [comment] 2023-07-13 14:41
#26 could fix this, just awaiting code review. The changes include a complete rewrite on the click events which should change the logic behind the crash and also uses Minecraft's own copy to clipboard method which should also fix problems caused by Java's simpler method.

Once something is out I will update this issue - would be nice if someone who could reproduce these issues in the past tested the mod again.

**Comment by tierrif** [comment] 2023-07-14 22:40
Someone who can reproduce this please test 1.10.0+1.20.1 and see if you can still reproduce the same issue. Thanks.

https://github.com/tierrif/chat-utils/releases/tag/1.10.0%2B1.20.1

**Comment by QarthO** [comment] 2023-07-15 11:59
Hey! I updated and tested this on my machine that was freezing before the update... and it worked!
This is great! Thanks so much for fixing it. Great response time too. 
I've got some other things with the new keybind, but ill create a new issue since this one is now solved

**Comment by tierrif** [comment] 2023-07-15 12:31
I'm happy it got fixed. As the OP didn't comment on this for a while, I will close this.

**Closed by tierrif** 2023-07-15 12:31 UTC
Labels: bug
