### ISSUE TITLE
Incompatibility with essential

### ISSUE THREAD

**Issue by Moonyol** [tierrif/chat-utils#23] opened 2023-06-17 09:02 UTC
I am using [Chat Utils 1.9.0](https://github.com/tierrif/chat-utils/releases/tag/1.9.0) and [Essential 1-19](https://www.curseforge.com/minecraft/mc-mods/essential-mod/files/3820968) on Fabric 0.14.19-1.19.4 if I attempt to copy a message the game will crash
![image](https://github.com/tierrif/chat-utils/assets/92951072/8fb1331d-4f35-4219-873d-9be5548449b0)

**Comment by tierrif** [comment] 2023-06-25 15:34
Tested with ChatUtils 1.9.0 and Essential 1.2.1.6, cannot reproduce under the following ChatUtils settings:
```json
{
  "ChatUtils": {
    "copyToClipboardMessage": "\u00269Click to copy to clipboard.",
    "previewContent": true,
    "copyColorsIfAny": true,
    "copyHexColors": true,
    "antiSpam": true,
    "antiSpamRange": 16,
    "tooltipEnabled": true,
    "enabled": true,
    "enableChatPersist": true,
    "enableCommandPersist": true
  }
}
```

Could you post the contents of your `.minecraft/config/chatutils/config.json` file? If you still can reproduce under my settings, please test under an unedited configuration of `Essential`.

Thanks

**Comment by tierrif** [comment] 2023-07-13 14:43
Could #22 be related?

**Comment by tierrif** [comment] 2023-07-16 09:54
Closing for inactivity, I'll easily assume this is fixed after 1.10.0+1.20.1.

**Comment by Moonyol** [comment] 2023-10-01 11:13
it still happens in 1.10.1

**Comment by tierrif** [comment] 2023-11-06 21:08
This at this point is probably related to #40. If not more info is given about this in the coming days I will close this again.

**Closed** 2024-02-05 22:30 UTC
Labels: incompatibility, missing info
