### ISSUE TITLE
Color code characters showing up on copied text

### ISSUE THREAD

**Issue by Fluboxer** [tierrif/chat-utils#35] opened 2023-08-14 10:51 UTC
Long story short - I saw spike of activity and commits, got my hands on sources and compiled most recent version 3a1cd358fed1f107a090099ae0b8b850f973618f into a jar and then got it in my client to see if it fixed stuff. It did! Mostly... (more on that later)

![2023-08-14_13 10 27](https://github.com/tierrif/chat-utils/assets/36457056/cfb65f36-169b-42d7-aff0-21a3d827ae24)

However, while I was testing stuff, I missclicked on screenshot taken message and it crashed minecraft. After few more tests I found out that it can be reproduced reliably - just take screenshot and try to copy message about screenshot 
No idea if it is from new commits or it was always here

![изображение](https://github.com/tierrif/chat-utils/assets/36457056/4ebba8f8-1813-4c92-b974-5f276026433b)

Other mods:
  [✔] 1.19-fullbright-1.0.2
  [✔] borderless-mining-1.1.8+1.20.1
  [✔] c2me-fabric-mc1.20.1-0.2.0+alpha.10.96
  [✔] cloth-config-11.1.106-fabric
  [✔] coordinatelist-1.5.0-1.20
  [✔] dashloader-5.0.0-beta.1+1.20.0
  [✔] Debugify-1.20.1+2.0
  [✔] dulkirmod-fabric-1.0.1
  [✔] enhancedblockentities-0.9+1.20
  [✔] entityculling-fabric-1.6.2-mc1.20
  [✔] fabric-api-0.86.1+1.20.1
  [✔] fabric-language-kotlin-1.10.8+kotlin.1.9.0
  [✔] ferritecore-6.0.0-fabric
  [✔] ImmediatelyFast-1.1.27+1.20.1
  [✔] indium-1.0.21+mc1.20.1
  [✔] language-reload-1.5.8+1.20.1
  [✔] lazydfu-0.1.3
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] memoryleakfix-fabric-1.17+-1.1.1
  [✔] midnightlib-fabric-1.4.1.1
  [✔] modelfix-1.14-fabric
  [✔] modmenu-7.2.1
  [✔] moreculling-1.20-0.18.1
  [✔] MouseTweaks-fabric-mc1.20-2.25
  [✔] NoChatReports-FABRIC-1.20.1-v2.2.2
  [✔] skyblocker-1.11.1-beta-053dd6f+1.20.1
  [✔] sodium-extra-0.4.25+mc1.20.1-build.108
  [✔] sodium-fabric-mc1.20-0.4.10+build.27
  [✔] yet-another-config-lib-fabric-3.1.0+1.20
  [✔] Zoomify-2.11.0

[crash-2023-08-14_13.16.39-client.txt](https://github.com/tierrif/chat-utils/files/12333759/crash-2023-08-14_13.16.39-client.txt)

**Comment by tierrif** [comment] 2023-10-20 10:40
I can't reproduce this after updating to 1.10.2+1.20.2, perhaps try this version?

**Comment by tierrif** [comment] 2024-02-05 22:39
At this point this is a duplicate of #29.

**Closed by tierrif** 2024-02-05 22:39 UTC
Labels: bug
