### ISSUE TITLE
ChatUtils 1.10.1+1.20.2

### ISSUE THREAD

**Issue by MadisonMadi** [tierrif/chat-utils#41] opened 2023-11-05 19:09 UTC
**Describe the bug**
Minecraft Instance doesn't load, and crashes instead.

**To Reproduce**
1. add mod (version 1.10.2+1.20.2
2. launch instance
3. check error log
4. see paste bin below

**PASTE BIN**
- https://pastebin.com/q7LXyCvs

**Client information**
 - OS: Windows
 - Minecraft: [Fabric 1.20.1] 
 - Mod version: [1.10.0+1.20.1]
 - Other mods: 

**Additional context**
upon selecting version 1.10.1+1.20.1 it does work. so this is clearly an issue from 1.10.2+1.20.2!

**Comment by tierrif** [comment] 2023-11-05 20:21
1.10.2+1.20.2 is not meant to work with Fabric 1.20.1. There's already an issue open regarding retrocompatibility on new additions to the 1.20.2 update (#40). If you believe the issue is something else though, please let me know, or I'll close this.

**Closed** 2023-11-06 21:04 UTC
